-- Schema exposed by PostgREST (PGRST_DB_SCHEMAS=api)
CREATE SCHEMA IF NOT EXISTS api;

CREATE TABLE IF NOT EXISTS api.tasks (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      TEXT NOT NULL,
  done       BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Role used for anonymous requests (PGRST_DB_ANON_ROLE=web_anon)
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'web_anon') THEN
    CREATE ROLE web_anon NOLOGIN;
  END IF;
END
$$;

GRANT USAGE ON SCHEMA api TO web_anon;
GRANT SELECT, INSERT ON api.tasks TO web_anon;

-- PostgREST logs in as the Secret's user and switches to web_anon per request
GRANT web_anon TO CURRENT_USER;

INSERT INTO api.tasks (title)
SELECT 'First task, inserted via SQL'
WHERE NOT EXISTS (SELECT FROM api.tasks);
